# Generated by Django 4.1.2 on 2024-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicado',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='libro_id',
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
