# Generated by Django 4.1.2 on 2024-07-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_rename_fecha_publicado_libro_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('Adultos', 'Adultos'), ('Niños', 'Niños'), ('Para todos', 'Para todos')], default='Para todos', max_length=20),
        ),
    ]
